name: Minor Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract and increment version
      id: versioning
      run: |
        # Extract current version and name from modinfo.ini
        current_version=$(grep '^version' modinfo.ini | awk -F '=' '{print $2}' | xargs)
        name=$(grep '^name' modinfo.ini | awk -F '=' '{print $2}' | xargs)
        echo "Current version: $current_version"
        echo "Mod name: $name"

        # Bump minor version and reset patch
        IFS='.' read -r major minor patch <<< "$current_version"
        minor=$((minor + 1))
        patch=0
        new_version="${major}.${minor}.${patch}"

        # Update modinfo.ini
        sed -i "s/^version = .*/version = $new_version/" modinfo.ini

        # Format file/release name
        zipname="${name// /_}_v${new_version}"  # Replace spaces with underscores for the file
        releasename="${name} v${new_version}"  # Keep original spacing for display

        echo "New version: $new_version"
        echo "Zip name: $zipname"
        echo "Release name: $releasename"

        # Set outputs
        echo "version=$new_version" >> $GITHUB_OUTPUT
        echo "zipname=$zipname" >> $GITHUB_OUTPUT
        echo "releasename=$releasename" >> $GITHUB_OUTPUT

    - name: Get Nexus Mod Stats
      id: nexus_stats
      run: |
        MOD_ID=1220
        GAME_NAME=monsterhunterwilds
        API_KEY=${{ secrets.NEXUS_API_KEY }}  # Store your Nexus API key in GitHub secrets
        RESPONSE=$(curl -s -H "apikey: $API_KEY" "https://api.nexusmods.com/v1/games/$GAME_NAME/mods/$MOD_ID.json")

        # Extract the download count from the response
        DOWNLOADS=$(echo "$RESPONSE" | jq '.mod_downloads')
        
        # Format the download count with commas (e.g., 3539 -> 3,539)
        FORMATTED_DOWNLOADS=$(printf "%'d" $DOWNLOADS)

        echo "Current download count: $FORMATTED_DOWNLOADS"
        echo "downloads=$FORMATTED_DOWNLOADS" >> $GITHUB_OUTPUT

    - name: Update README with new version and badges
      run: |
        # Update version-related links and badges in README.md
        sed -i "s|https://github.com/mashirochan/MHWS-FilterSOSList/releases/tag/v[0-9]*\.[0-9]*\.[0-9]*|https://github.com/mashirochan/MHWS-FilterSOSList/releases/tag/v${{ steps.versioning.outputs.version }}|g" README.md
        sed -i "s|<img src=\"https://img.shields.io/badge/version-[^\"]*\"|<img src=\"https://img.shields.io/badge/version-${{ steps.versioning.outputs.version }}-ff6262\" alt=\"version\"|g" README.md
        sed -i "s|<img src=\"https://img.shields.io/badge/downloads-[^\"]*\"|<img src=\"https://img.shields.io/badge/downloads-${{ steps.nexus_stats.outputs.downloads }}-ff6262\" alt=\"downloads\"|g" README.md

    - name: Commit updated version and README
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add modinfo.ini README.md
        git commit -m "Bump version to ${{ steps.versioning.outputs.version }} and update README"
        git push

    - name: Zip selected files
      run: |
        zip -r "${{ steps.versioning.outputs.zipname }}.zip" reframework/autorun Cover.png modinfo.ini

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.versioning.outputs.version }}
        name: ${{ steps.versioning.outputs.releasename }}
        files: ${{ steps.versioning.outputs.zipname }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
